// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfa8ab21VzJaCynHu9Z8tHwIXxpGPcs-4',
    appId: '1:652356468536:web:88fbd5be5635c51f580bcd',
    messagingSenderId: '652356468536',
    projectId: 'pastifyhubstores',
    authDomain: 'pastifyhubstores.firebaseapp.com',
    storageBucket: 'pastifyhubstores.firebasestorage.app',
    measurementId: 'G-Z8XYC0D366',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXyPW55yWrJGE3UF3iumMzt00tNuU2s4w',
    appId: '1:652356468536:android:58cdcfbd255f530a580bcd',
    messagingSenderId: '652356468536',
    projectId: 'pastifyhubstores',
    storageBucket: 'pastifyhubstores.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBtvpEnXA7vLGmtOyOe8ZBq9UgxMWOsds',
    appId: '1:652356468536:ios:40f485e01f2b1805580bcd',
    messagingSenderId: '652356468536',
    projectId: 'pastifyhubstores',
    storageBucket: 'pastifyhubstores.firebasestorage.app',
    iosBundleId: 'pastifyhubstores.example.pastifyhubstores',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBtvpEnXA7vLGmtOyOe8ZBq9UgxMWOsds',
    appId: '1:652356468536:ios:40f485e01f2b1805580bcd',
    messagingSenderId: '652356468536',
    projectId: 'pastifyhubstores',
    storageBucket: 'pastifyhubstores.firebasestorage.app',
    iosBundleId: 'pastifyhubstores.example.pastifyhubstores',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfa8ab21VzJaCynHu9Z8tHwIXxpGPcs-4',
    appId: '1:652356468536:web:fdb294ac13dde9b4580bcd',
    messagingSenderId: '652356468536',
    projectId: 'pastifyhubstores',
    authDomain: 'pastifyhubstores.firebaseapp.com',
    storageBucket: 'pastifyhubstores.firebasestorage.app',
    measurementId: 'G-9NXKTQB5VL',
  );
}
